CREATE DATABASE LIVARIA;

USE LIVRARIA;

STATUS;


 
CREATE DATABASE ATHENA;

DEFAULT CHARACTER SET UTF8MB4
DEFAULT COLLATE UTF8MB4_UNICODE_CI;

USE ATHENA;

CREATE TABLE FUNCIONARIO(NOME VARCHAR(30) NOT NULL, SOBRENOME VARCHAR(20) NOT NULL, EMAIL VARCHAR(30) NOT NULL, 
CPF CHAR(11) NOT NULL, SEXO enum ('M', 'F') NOT NULL CARGO VARCHAR(30), DATA_ADMISSAO DATE NOT NULL
);

CREATE TABLE EMPRESA( ID_EMPRESA INT PRIMARY KEY AUTO_INCREMENT NOT NULL, CNPJ CHAR(14) NOT NULL, 
NOME_EMPRESA VARCHAR(99) NOT NULL, TELEFONE CHAR(13) NOT NULL, EMAIL VARCHAR(30) NOT NULL,  
);

CREATE TABLE LIVRO(ID_LIVRO INT PRIMARY KEY AUTO_INCREMENT NOT NULL, TITULO VACHAR(100) NOT NULL, AUTOR VACHAR(30) NOT NULL, 
ANO INT(4) NOT NULL, GENERO VARCHAR(30) NOT NULL, IDIOMA VARCHAR(30) NOT NULL, VOLUME INT, EDICAO INT,
IMAGEM LONGBLOG NOT NULL, DATA_REGISTRO DATE NOT NULL, PAGINAS INT, DESCRICAO VARCHAR(500), STATUS ENUM('D','I') NOT NULL
); 

CREATE TABLE EDITORA(ID_EDITORA INT PRIMARY KEY AUTO_INCREMENT NOT NULL, NOME_EDITORA VARCHAR(30) NOT NULL /*NACIONALIDADE
OU CONTATO COMO OPÇÃO*/
);

CREATE TABLE RESERVA(ID_RESERVA INT PRIMARY KEY AUTO_INCREMENT NOT NULL, DATA_RESERVA DATE NOT NULL, PRAZO_RESERVA DATE
NOT NULL, SITUACAO_RESERVA ENUM('X','X') NOT NULL, /*PONTO A SER DISCUTIDO NA REUNIÃO*/, ID_LIVRO INT, CONSTRAINT FK_IDLIVRO
FOREIGN KEY (ID_LIVRO) REFERENCES LIVRO (ID_LIVRO) /*VAI TER CHAVE ESTRANGEIRA PARA FAZER LIGAÇÃO DE USUARIO?*/
);

CREATE TABLE AGENDAMENTO (ID_AGENDAMENTO INT PRIMARY KEY AUTO_INCREMENT NOT NULL, DATA_RETIRADA DATE, 
DATA_ENTREGA DATE, ID_LIVRO INT, CONSTRAINT FK_IDLIVRO FOREIGN KEY (ID_LIVRO) REFERENCES LIVRO (ID_LIVRO) /*VAI TER CHAVE
ESTRANGEIRA PARA FAZER LIGAÇÃO DE USUARIO?*/
);

CREATE TABLE USUARIO(ID_USARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT, SENHA_USUARIO CHAR(10) NOT NULL, 
NIVEL_ACESSO ENUM('A','U') NOT NULL, SITUACAO_USUARIO ENUM('B','D') NOT NULL
);



